// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zigot.Infrastructure.Identity.Context;

#nullable disable

namespace Zigot.Infrastructure.Identity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240926211714_StartUp")]
    partial class StartUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Addresses.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endereco");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cep");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("pes_endereco", (string)null);
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Contacts.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("email");

                    b.Property<string>("OriginCity")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("cidade_origem");

                    b.Property<string>("OriginState")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("uf_origem");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("pes_contato", (string)null);
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cpf");

                    b.Property<string>("ElectoralTitle")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("titulo_eleitoral");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_emissao");

                    b.Property<string>("IssuingBody")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("orgao");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rg");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("euf");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("pes_documento", (string)null);
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.DomainModel.ProcessModel.FederalModel.FederalDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BucketReferenceCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("codigo_referencia_bucket");

                    b.Property<string>("DocumentDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao_documento");

                    b.Property<long>("FederalRegistrationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FederalRegistrationId");

                    b.ToTable("reg_federal_documentos", (string)null);
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.DomainModel.ProcessModel.FederalModel.FederalRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean")
                        .HasColumnName("finalizado");

                    b.Property<long>("ProcessId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId")
                        .IsUnique();

                    b.ToTable("reg_federal", (string)null);
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.DomainModel.ProcessModel.Process", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Caliber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("calibre");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WeaponRegisterDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("WeaponRegistrationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_registro");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("arma");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("pes_processo", (string)null);
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("FatherFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_pai");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_filhos");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado_civil");

                    b.Property<string>("MotherFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_mae");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profissao");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.HasKey("Id");

                    b.ToTable("pes_cliente", (string)null);
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Addresses.Address", b =>
                {
                    b.HasOne("Zigot.Core.Domain.Contract.Persons.Person", "Person")
                        .WithOne("Address")
                        .HasForeignKey("Zigot.Core.Domain.Contract.Addresses.Address", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Contacts.Contact", b =>
                {
                    b.HasOne("Zigot.Core.Domain.Contract.Persons.Person", "Person")
                        .WithOne("Contact")
                        .HasForeignKey("Zigot.Core.Domain.Contract.Contacts.Contact", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.Document", b =>
                {
                    b.HasOne("Zigot.Core.Domain.Contract.Persons.Person", "Person")
                        .WithOne("Documents")
                        .HasForeignKey("Zigot.Core.Domain.Contract.Persons.Document", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.DomainModel.ProcessModel.FederalModel.FederalDocument", b =>
                {
                    b.HasOne("Zigot.Core.Domain.Contract.Persons.DomainModel.ProcessModel.FederalModel.FederalRegistration", "FederalRegistration")
                        .WithMany("Documents")
                        .HasForeignKey("FederalRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FederalRegistration");
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.DomainModel.ProcessModel.FederalModel.FederalRegistration", b =>
                {
                    b.HasOne("Zigot.Core.Domain.Contract.Persons.DomainModel.ProcessModel.Process", "Process")
                        .WithOne("FederalRegistration")
                        .HasForeignKey("Zigot.Core.Domain.Contract.Persons.DomainModel.ProcessModel.FederalModel.FederalRegistration", "ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.DomainModel.ProcessModel.Process", b =>
                {
                    b.HasOne("Zigot.Core.Domain.Contract.Persons.Person", "Person")
                        .WithMany("Processes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.DomainModel.ProcessModel.FederalModel.FederalRegistration", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.DomainModel.ProcessModel.Process", b =>
                {
                    b.Navigation("FederalRegistration")
                        .IsRequired();
                });

            modelBuilder.Entity("Zigot.Core.Domain.Contract.Persons.Person", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Documents")
                        .IsRequired();

                    b.Navigation("Processes");
                });
#pragma warning restore 612, 618
        }
    }
}
